name: Build SpotiMP3

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          echo "$env:USERPROFILE\go\bin" >> $env:GITHUB_PATH

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build app
        run: wails build -platform windows/amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SpotiMP3
          path: build/bin/*.exe
